package ids.tx.bpmn;

public enum BPMNNodeType
{
	TASK,
	SERVICE_TASK,
	RECEIVE_TASK,
	SEND_TASK,
	HUMAN_INTERACTION_TASK,
	BUSINESS_RULE_TASK,
	SCRIPT_TASK,
	SUBPROCESS,
	INTERMEDIATE_CATCH_EVENT,
	INTERMEDIATE_THROW_EVENT,
	START_EVENT,
	END_EVENT,
	BOUNDARY_EVENT,
	EXCLUSIVE_GATEWAY,
	INCLUSIVE_GATEWAY,
	PARALLEL_GATEWAY,
	COMPLEX_GATEWAY,
	EVENT_BASED_GATEWAY,
	CALL_ACTIVITY,
	GLOBAL_TASK
}